export { default as LandingPage } from 'pages/LandingPage'
export { default as AddAPlacePage } from 'pages/AddAPlacePage'
export { default as LoginPage } from 'pages/LoginPage'
export { default as UserRegistrationPage } from 'pages/UserRegistrationPage'
export { default as PlacesDetailPage } from 'pages/PlacesDetailPage'
export { default as UserProfilePage } from 'pages/UserProfilePage'
export { default as MapPage } from 'pages/MapPage/index'